import "./globals.css";
import NavBar from "./components/NavBar";
import SkipLink from "./components/SkipLink";

export const metadata = {
  title: "Dictionary Web App",
  description: "Generated by create next app",
  icons: {
    icon: "./assets/images/favicon-32x32.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="px-12 dark:bg-black">
        <SkipLink />
        <NavBar />
        <main id="main-content" className="max-w-3xl m-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
